"""Add favorite products with cascade deletes

Revision ID: 06182fd48224
Revises: 6743597d29ad
Create Date: 2026-04-17 13:03:27.915602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06182fd48224'
down_revision: Union[str, Sequence[str], None] = '6743597d29ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'product_id', name='uq_favorite_item')
    )
    with op.batch_alter_table('favorite_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_products_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_products_id'))

    op.drop_table('favorite_products')
    # ### end Alembic commands ###
