"""Add status to tenant_product_mappings

Revision ID: 824b9ab98231
Revises: 6812c0ffa6b9
Create Date: 2026-02-18 11:59:44.127479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '824b9ab98231'
down_revision: Union[str, Sequence[str], None] = '6812c0ffa6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_user_mappings', 'role_name')
    op.add_column('tenant_product_mappings', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenant_product_mappings', 'status')
    op.add_column('role_user_mappings', sa.Column('role_name', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
