"""add last_heartbeat to product_sessions

Revision ID: b749ca7f527a
Revises: add_favorite_bool_col
Create Date: 2026-04-28 16:26:53.367588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b749ca7f527a'
down_revision: Union[str, Sequence[str], None] = 'add_favorite_bool_col'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_products', schema=None) as batch_op:
        batch_op.alter_column('favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('product_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_heartbeat', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sessions', schema=None) as batch_op:
        batch_op.drop_column('last_heartbeat')

    with op.batch_alter_table('favorite_products', schema=None) as batch_op:
        batch_op.alter_column('favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
