"""Add details column to Product

Revision ID: bb4bdd639ce1
Revises: 2d5c7707efe3
Create Date: 2026-03-03 15:14:00.642313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4bdd639ce1'
down_revision: Union[str, Sequence[str], None] = '2d5c7707efe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('details', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'details')
    # ### end Alembic commands ###
